import { defineConfig } from "vite";

export default defineConfig({
  base: "./",
  build: {
    outDir: "dist",
    assetsDir: "assets",
    rollupOptions: {
      external: [
        "./libs/splide/splide.min.js",
        "./libs/swipper/swiper-bundle.min.js",
        "./libs/imask/imask.min.js",
        "./libs/toastify/toastify.min.js",
        "./libs/clipboard/clipboard.min.js",
        "./libs/gsap/gsap.min.js",
      ],
      input: {
        main: "index.html",
        clubs: "clubs.html",
        clubsAtlant: "clubs-atlant.html",
        clubsAtmosphere: "clubs-atmosphere.html",
        clubsBirusova: "clubs-birusova.html",
        clubsHamovniki: "clubs-hamovniki.html",
        clubsSails: "clubs-sails.html",
        ourClubs: "our-clubs.html",
        team: "team.html",
        teamDetail: "team-detail.html",
        reviews: "reviews.html",
        fitnes: "fitnes.html",
        servicesDetail: "services-detail.html",
        widget: "widget.html", // test widget
        // partners: "partners.html",
        investors: "investors.html",
        contacts: "contacts.html",
        subscription: "subscription.html",
        subscriptionDetail: "subscription-detail.html",
        blog: "blog.html",
        blogDetail: "blog-detail.html",
        news: "news.html",
        newsDetail: "news-detail.html",
        promotions: "promotions.html",
        notFound: "not-found.html",
        marketing: "marketing.html",
        aboutUs: "about-us.html",
        events: "events.html",
        eventsDetail: "events-detail.html",
      },
    },
  },
});
